### ISSUE TITLE
Constraints on the input for `add_edge` when it is a list

### ISSUE THREAD

**Issue by gbaian10** [langchain-ai/langgraph#1462] opened 2024-08-25 01:24 UTC
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the [LangGraph](https://langchain-ai.github.io/langgraph/)/LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangGraph/LangChain rather than my code.
- [X] I am sure this is better as an issue [rather than a GitHub discussion](https://github.com/langchain-ai/langgraph/discussions/new/choose), since this is a LangGraph bug and not a design question.

### Example Code

Q1: When the start_key in `add_edge` is a list, the end_key can't be `__end__`.
```py
from langgraph.graph import END, MessageGraph, StateGraph


def foo(state: MessageGraph) -> None:
    return


graph_builder = StateGraph(MessageGraph)
graph_builder.set_entry_point("enter")
for node in ["enter", "A", "B"]:
    graph_builder.add_node(node, foo)
graph_builder.add_conditional_edges("enter", lambda _: True, {True: "A", False: "B"})

graph_builder.add_edge(["A", "B"], END)
# graph_builder.add_edge("A", END)
# graph_builder.add_edge("B", END)

app = graph_builder.compile()
```

Q2: When the input is a `list`, you must add the `node` before adding an `edge`.
However, if the input is a str, you don't necessarily need to add the `node` first.
```py
from langgraph.graph import END, MessageGraph, StateGraph


def foo(state: MessageGraph) -> None:
    return


graph_builder = StateGraph(MessageGraph)
graph_builder.set_entry_point("enter")

graph_builder.add_edge(["A", "B"], END)
# graph_builder.add_edge("A", END)
# graph_builder.add_edge("B", END)

for node in ["enter", "A", "B"]:
    graph_builder.add_node(node, foo)
graph_builder.add_conditional_edges("enter", lambda _: True, {True: "A", False: "B"})

app = graph_builder.compile()
```

#### Q1

```shell
Traceback (most recent call last):
  File ".\issue.py", line 14, in <module>
    graph_builder.add_edge(["A", "B"], END)
  File ".\langgraph\graph\state.py", line 378, in add_edge
    raise ValueError(f"Need to add_node `{end_key}` first")
ValueError: Need to add_node `__end__` first
```

#### Q2

```shell
Traceback (most recent call last):
  File ".\issue.py", line 11, in <module>
    graph_builder.add_edge(["A", "B"], END)
  File ".\langgraph\graph\state.py", line 374, in add_edge
    raise ValueError(f"Need to add_node `{start}` first")
ValueError: Need to add_node `A` first
```

### Description

Basically, Q1 is a subissue of Q2.

![image](https://github.com/user-attachments/assets/f4a8ccef-fa73-4951-823c-8ee9d61231e6)

Is it necessary to check if the node has already been added in the high-level module of the code?
I removed these parts and it still runs, and it can solve the problem mentioned above.
At least the result of `draw_mermaid_png` is the same. I haven't conducted further tests.

---

![image](https://github.com/user-attachments/assets/81f9d211-a15d-438f-b3ed-5fd47da21dc2)

However, I found that when the input is a `list`, it uses `waiting_edges`, but when the input is a `str`, it doesn't use `waiting_edges`.

After further observation, I noticed that during subsequent compilation, nodes are always added first.
At this point, it makes me reconsider whether the previous check for node existence in add_edge is necessary.

![image](https://github.com/user-attachments/assets/566c87a5-8a95-417b-bc19-ec54cc961490)

Upon further observation, I found that the underlying behavior differs when the input is a string or a list, such as with different `channel_name` values.
Since I currently don't understand the underlying workings of langgraph (e.g., how channels operate), I'm unsure if directly modifying the preliminary checks in the higher-level module's `add_edge` might cause additional issues.

---

A simple question to summarize the above explanation: Will the outputs be exactly the same for the following two inputs?

```py
graph_builder.add_edge(["A", "B"], END)
```

```py
graph_builder.add_edge("A", END)
graph_builder.add_edge("B", END)
```

### System Info

langgraph==0.2.14

platform==windows
python-version==3.12.5

**Comment by bianbianzhu** [comment] 2024-08-25 03:17
I am using the langgraphJS and found some bugs related to the two types of inputs you've mentioned.

1. Fan-out and fan-in with extra steps
![image](https://github.com/user-attachments/assets/e631f152-eb04-4a60-9ae5-a04e661147f0)

The code is derived from the [Create branches for parallel execution](https://langchain-ai.github.io/langgraphjs/how-tos/branching/) offical doc.
```typescript
workflow
  .addNode("a", nodeA.call.bind(nodeA))
  .addNode("b", nodeB.call.bind(nodeB))
  .addNode("b2", nodeB2.call.bind(nodeB2))
  .addNode("c", nodeC.call.bind(nodeC))
  .addNode("d", nodeD.call.bind(nodeD))
  .addEdge(START, "a")
  .addEdge("a", "b")
  .addEdge("b", "b2")
  .addEdge("a", "c")

  // >>> method 1 (right way) <<<
  .addEdge(["b2", "c"], "d")

  // method 2 (wrong way) - The following will add one extra `I'm D` to the aggregate
  // .addEdge("b2", "d")
  // .addEdge("c", "d")

  .addEdge("d", END);
```
The output from method 1 - ✅
```
// from method 1
Adding I'm A to
Adding I'm B to I'm A
Adding I'm C to I'm A
Adding I'm B2 to I'm A,I'm B,I'm C
Adding I'm D to I'm A,I'm B,I'm C,I'm B2
{ aggregate: [ "I'm A", "I'm B", "I'm C", "I'm B2", "I'm D" ] }
```
The output from method 2 - ❌ an extra "I'm D" is presented.
```
// From method 2
Adding I'm A to 
Adding I'm B to I'm A
Adding I'm C to I'm A
Adding I'm B2 to I'm A,I'm B,I'm C
Adding I'm D to I'm A,I'm B,I'm C
Adding I'm D to I'm A,I'm B,I'm C,I'm B2,I'm D
{
  aggregate: [ "I'm A", "I'm B", "I'm C", "I'm B2", "I'm D", "I'm D" ]
}
```

2. 

```typescript
function routeToBCorCD(state: GraphState): string[] {
  const { which } = state;
  return which === "bc" ? ["B", "C1"] : ["B", "C2"];
}

workflow
  .addNode("A", NodeA.call.bind(NodeA))

  .addNode("C2", NodeC2.call.bind(NodeC2))

  .addNode("B", NodeB.call.bind(NodeB))

  .addNode("C1", NodeC1.call.bind(NodeC1))

  .addNode("D", NodeD.call.bind(NodeD))

  .addEdge(START, "A")

  .addConditionalEdges("A", routeToBCorCD, { B: "B", C1: "C1", C2: "C2" })

  .addEdge(["B", "C1", "C2"], "D") // This method to fan-in

  .addEdge("D", END);
```
```typescript
 const res = await app.invoke({
    messages: [],
    which: "bc",
  });
``` 
Output: ❌ "I am D" is missing
```
Add I am A to []

Add I am B to [I am A]

Add I am C1 to [I am A]

Add I am D to [I am A,I am B,I am C1]
{ messages: [ 'I am A', 'I am B', 'I am C1' ], which: 'bc' }
```
Must use the following method to fan-in to avoid this bug
```typescript
  .addEdge("B", "D")
  .addEdge("C1", "D")
  .addEdge("C2", "D")
```

**Comment by gbaian10** [comment] 2024-08-25 04:09
https://langchain-ai.github.io/langgraph/how-tos/branching/

```py
import operator
from typing import Annotated, TypedDict

from langgraph.graph import END, START, StateGraph


class State(TypedDict):
    aggregate: Annotated[list, operator.add]


class ReturnNodeValue:
    def __init__(self, node_secret: str) -> None:
        self._value = node_secret

    def __call__(self, state: State) -> State:
        print(f"Adding {self._value} to {state['aggregate']}")
        return {"aggregate": [self._value]}


builder = StateGraph(State)
builder.add_node("a", ReturnNodeValue("I'm A"))
builder.add_edge(START, "a")
builder.add_node("b", ReturnNodeValue("I'm B"))
builder.add_node("b2", ReturnNodeValue("I'm B2"))
builder.add_node("c", ReturnNodeValue("I'm C"))
builder.add_node("d", ReturnNodeValue("I'm D"))
builder.add_edge("a", "b")
builder.add_edge("a", "c")
builder.add_edge("b", "b2")

builder.add_edge(["b2", "c"], "d")  # will get one D output
# builder.add_edge("b2", "d")
# builder.add_edge("c", "d")  # will get extra D output

builder.add_edge("d", END)
graph = builder.compile()

graph.invoke({"aggregate": []})
```

![image](https://github.com/user-attachments/assets/b7c11fe9-4997-430b-afa6-46e9a6c463d5)


```plain
# list

Adding I'm A to []
Adding I'm B to ["I'm A"]
Adding I'm C to ["I'm A"]
Adding I'm B2 to ["I'm A", "I'm B", "I'm C"]
Adding I'm D to ["I'm A", "I'm B", "I'm C", "I'm B2"]
```

```plain
# str

Adding I'm A to []
Adding I'm B to ["I'm A"]
Adding I'm C to ["I'm A"]
Adding I'm B2 to ["I'm A", "I'm B", "I'm C"]
Adding I'm D to ["I'm A", "I'm B", "I'm C"]
Adding I'm D to ["I'm A", "I'm B", "I'm C", "I'm B2", "I'm D"]
```

From this example, I tried two types of input (using str twice or a list once), and the results were indeed different.

I `guess` that using a list requires waiting for all the results to arrive before outputting the aggregated results at once. However, using str separately means two independent parallel paths are running, right?

---

```py
import operator
from typing import Annotated, TypedDict

from langgraph.graph import END, START, StateGraph


class State(TypedDict):
    aggregate: Annotated[list, operator.add]


class ReturnNodeValue:
    def __init__(self, node_secret: str) -> None:
        self._value = node_secret

    def __call__(self, state: State) -> State:
        print(f"Adding {self._value} to {state['aggregate']}")
        return {"aggregate": [self._value]}


builder = StateGraph(State)
builder.add_node("a", ReturnNodeValue("I'm A"))
builder.add_edge(START, "a")
builder.add_node("b", ReturnNodeValue("I'm B"))
builder.add_node("c", ReturnNodeValue("I'm C"))
builder.add_node("d", ReturnNodeValue("I'm D"))
builder.add_edge("a", "b")
builder.add_edge("a", "c")

builder.add_edge(["b", "c"], "d")  # will get a D output
# builder.add_edge("b", "d")
# builder.add_edge("c", "d")  # also get a D output

builder.add_edge("d", END)
graph = builder.compile()

graph.invoke({"aggregate": []})
```

![image](https://github.com/user-attachments/assets/6a0c83a7-0e13-43be-b82e-c7ec8a04f6bd)

```plain
# list and str

Adding I'm A to []
Adding I'm B to ["I'm A"]
Adding I'm C to ["I'm A"]
Adding I'm D to ["I'm A", "I'm B", "I'm C"]
```

However, in this situation, it always outputs just one "D."
Could you help me understand where I might be mistaken?

**Comment by gbaian10** [comment] 2024-08-25 04:19
```py
import operator
from typing import Annotated, TypedDict

from langgraph.graph import END, START, StateGraph


class State(TypedDict):
    aggregate: Annotated[list, operator.add]


class ReturnNodeValue:
    def __init__(self, node_secret: str) -> None:
        self._value = node_secret

    def __call__(self, state: State) -> State:
        print(f"Adding {self._value} to {state['aggregate']}")
        return {"aggregate": [self._value]}


builder = StateGraph(State)

builder.add_edge(["b2", "c"], "d")  # Move it before add_node.

builder.add_node("a", ReturnNodeValue("I'm A"))
builder.add_edge(START, "a")
builder.add_node("b", ReturnNodeValue("I'm B"))
builder.add_node("b2", ReturnNodeValue("I'm B2"))
builder.add_node("c", ReturnNodeValue("I'm C"))
builder.add_node("d", ReturnNodeValue("I'm D"))
builder.add_edge("a", "b")
builder.add_edge("a", "c")
builder.add_edge("b", "b2")
builder.add_edge("d", END)
graph = builder.compile()

graph.invoke({"aggregate": []})
```

Additionally, comment on the pre-checks of the source code.

![image](https://github.com/user-attachments/assets/8d62c7fc-6965-4a33-b021-110694395645)

It can work and the results are the same, is the pre-check necessary?

**Comment by gbaian10** [comment] 2024-08-25 17:00
> As you can see, `I'm E` is missing here. 

The same issue can be reproduced in Python.

```py
import operator
from collections.abc import Sequence
from typing import Annotated

from langgraph.graph import END, START, StateGraph
from typing_extensions import TypedDict


class State(TypedDict):
    aggregate: Annotated[list, operator.add]
    which: str


class ReturnNodeValue:
    def __init__(self, node_secret: str) -> None:
        self._value = node_secret

    def __call__(self, state: State) -> State:
        print(f"Adding {self._value} to {state['aggregate']}")
        return {"aggregate": [self._value]}


builder = StateGraph(State)
builder.add_node("a", ReturnNodeValue("I'm A"))
builder.add_edge(START, "a")
builder.add_node("b", ReturnNodeValue("I'm B"))
builder.add_node("c", ReturnNodeValue("I'm C"))
builder.add_node("d", ReturnNodeValue("I'm D"))
builder.add_node("e", ReturnNodeValue("I'm E"))


def route_bc_or_cd(state: State) -> Sequence[str]:
    if state["which"] == "cd":
        return ["c", "d"]
    return ["b", "c"]


intermediates = ["b", "c", "d"]
builder.add_conditional_edges(
    "a",
    route_bc_or_cd,
    intermediates,
)

# for node in intermediates:
#     builder.add_edge(node, "e")
builder.add_edge(intermediates, "e")


builder.add_edge("e", END)
graph = builder.compile()
print(graph.invoke({"aggregate": [], "which": "bc"}))
# print(graph.invoke({"aggregate": [], "which": "cd"}))
```

**Comment by vbarda** [comment] 2024-08-27 16:43
@gbaian10 for the first part of your question:

> Q1: When the start_key in add_edge is a list, the end_key can't be __end__. 

this is fixed this in https://github.com/langchain-ai/langgraph/pull/1478

> Q2: When the input is a list, you must add the node before adding an edge. 

This is a good point, but we discussed internally and decided to keep this as is for an extra layer of validation

--- 

for the remainder of this discussion / questions / examples you listed:


```python
graph_builder.add_edge(["A", "B"], END)
```
^ This will triggers C after _both_ A and B have completed


```python
graph_builder.add_edge("A", END)
graph_builder.add_edge("B", END)
```
^ This will trigger C after either A or B have completed

In the last example you provided you can verify this by changing the edges to

```python
builder.add_edge(["b", "c"], "e")
builder.add_edge(["c", "d"], "e")
```

The reason why the previous code snippet with builder.add_edge(["b", "c", "d"], "e") didn't work is because you need all of the nodes (`b`, `c` and `d`) to complete which they can't in that case. 

Closing the issue as the library is working as intended -- thank you for the questions and thoughtful discussion.

**Closed by vbarda** 2024-08-27 16:43 UTC
