### ISSUE TITLE
Cannot start "langgraph up"

### ISSUE THREAD

**Issue by shanumas** [langchain-ai/langgraph#893] opened 2024-06-30 18:38 UTC
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the [LangGraph](https://langchain-ai.github.io/langgraph/)/LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangGraph/LangChain rather than my code.
- [X] I am sure this is better as an issue [rather than a GitHub discussion](https://github.com/langchain-ai/langgraph/discussions/new/choose), since this is a LangGraph bug and not a design question.

### Example Code

```python
langgraph up
```

### Error Message and Stack Trace (if applicable)

```shell
langgraph-api-1       | Not enough segments
langgraph-api-1       | 2024-06-28 00:22:33,709:ERROR:uvicorn.error Traceback (most recent call last):
langgraph-api-1       |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 732, in lifespan
langgraph-api-1       |     async with self.lifespan_context(app) as maybe_state:
langgraph-api-1       |   File "/usr/local/lib/python3.11/contextlib.py", line 210, in __aenter__
langgraph-api-1       |     return await anext(self.gen)
langgraph-api-1       |            ^^^^^^^^^^^^^^^^^^^^^
langgraph-api-1       |   File "/api/langgraph_api/lifespan.py", line 18, in lifespan
langgraph-api-1       | ValueError: License key is not valid
langgraph-api-1       | 
langgraph-api-1       | 2024-06-28 00:22:33,709:ERROR:uvicorn.error Application startup failed. Exiting.
langgraph-api-1 exited with code 3
```

### Description

I count not do "langgraph up" .  I get the above error.

### System Info

langgraph up

**Comment by hinthornw** [comment] 2024-07-01 06:11
Duplicate of #889

We are working on removing the license restrictions soon

**Closed by hinthornw** 2024-07-01 06:11 UTC

**Comment by shanumas** [comment] 2024-07-01 06:21
@hinthornw please do it as soon as possible.  It will help a lot of devs like me 😕

**Comment by hinthornw** [comment] 2024-07-01 16:08
Very much agreed! 

Reason for this is the postgres version is proprietary (for now); we made a sqlite version but sqlite just doesn't support the concurrency that we need to make the local experience suffiently good.

**Comment by shanumas** [comment] 2024-07-01 16:37
@hinthornw   If I revert my local-git back to pre-langgraphCloud state, will it work fine to run locally?

**Comment by vbarda** [comment] 2024-07-01 16:59
@shanumas if your question is about chat langchain, yes, you should be able to run it locally from an old branch. for langgraph cloud, we'll follow up with better instructions in chat langchain README and on the issues

**Comment by Factral** [comment] 2024-07-01 19:27
same error here

**Comment by vbarda** [comment] 2024-10-31 16:38
Hi folks! We just added more deployment options for LangGraph Platform (formerly LangGraph Cloud), including "Self-hosted Lite" - a limited free version. It is available to anyone with a free (developer) LangSmith account. Please check out the documentation to learn more: https://langchain-ai.github.io/langgraph/concepts/deployment_options/#self-hosted-lite. let me know if you have any questions!

**Comment by jeffersonRosman** [comment] 2024-12-30 03:14
Hello!
I still have the same problem? is it still ongoing?
